# Generated by Django 3.2 on 2022-08-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_addcart_myuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcart',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
