# Generated by Django 3.2 on 2022-08-30 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220830_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcart',
            name='discount_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addcart',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
