# Generated by Django 3.2 on 2022-08-31 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_auto_20220830_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('company_name', models.CharField(blank=True, max_length=70, null=True)),
                ('area_code', models.CharField(max_length=20)),
                ('primary_phone', models.CharField(max_length=20)),
                ('street_address', models.CharField(max_length=70)),
                ('zip_code', models.CharField(max_length=30)),
                ('busniess_address', models.BooleanField(default=False)),
                ('myuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
